USE FRETES;

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL,
  `SENHA` VARCHAR(50) NULL,
  `TIPO` VARCHAR(15) NULL,
  PRIMARY KEY (`ID_USUARIO`)
);

DROP TABLE IF EXISTS PRODUTO;
CREATE TABLE PRODUTO (
  `ID_PRODUTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL,
  `DESCRICAO` VARCHAR(200) NULL,
  `ORIGEM` VARCHAR(100) NULL,
  `DESTINO` VARCHAR(100) NULL,
  `CLIENTE` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_PRODUTO`));
